name: Build and Deploy to Production

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  extract_info:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version package.json -r"
      - name: Extract package name from package.json
        uses: sergeysova/jq-action@v2
        id: package
        with:
          cmd: "jq .name package.json -r"
      - name: Extract tagPath from flowcore.deployment.json
        uses: sergeysova/jq-action@v2
        id: tagPath
        with:
          cmd: "jq .tagPath flowcore.deployment.json -r"
    outputs:
      version: ${{ steps.version.outputs.value }}
      package: ${{ steps.package.outputs.value }}
      tagPath: ${{ steps.tagPath.outputs.tagPath }}

  build_docker:
    needs: extract_info
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.FLOWCORE_MACHINE_GITHUB_TOKEN }}
          submodules: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::305363105399:role/ECRGithubManager
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: int128/create-ecr-repository-action@v1
        with:
          repository: ${{ needs.extract_info.outputs.package }}
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ needs.extract_info.outputs.package }}
          IMAGE_TAG: ${{ needs.extract_info.outputs.version }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy:
    needs: [build_docker, extract_info]
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: flowcore-io/public-customer-sites-manifests
          ref: main
          path: manifest
          token: ${{ secrets.FLOWCORE_MACHINE_GITHUB_TOKEN }}
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.42.1
        with:
          cmd: yq --version
      - name: Update Image Version in the related HelmChart production configuration file
        run: |
          yq -i '.${{ needs.extract_info.outputs.tagPath }} = "${{ needs.extract_info.outputs.version }}"' manifest/configuration/azure-eu.yaml
      - name: Commit the changes
        run: |
          cd manifest
          git config --global user.email "flowcore_platform@flowcore.io"
          git config --global user.name "flowcore-machine"
          git add configuration/azure-eu.yaml
          git commit -m "chore(azure-eu): update ${{ needs.extract_info.outputs.tagPath }} to ${{ needs.extract_info.outputs.version }}"
          git push



